### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by TheMerchandise** [codeshaunted/monke#1]
Error in configuration process, project files may be invalid

**Comment by codeshaunted** [comment]
What is this supposed to mean? Are you using the included CMakeLists.txt?

**Comment by hemisemidemipresent** [comment]
I think it is because there was an issue when you use the GUI

[Here's an image of attempting to build the project using the GUI](https://media.discordapp.net/attachments/699781597515481159/919780168015421460/unknown.png)

on the command line though it works perfectly fine with `cmake --build <dir>` with `<dir>` being the base folder of this repo

**Comment by hemisemidemipresent** [comment]
I think many of the cpp files in the cryptolib thing can be removed since it makes the compilation time much longer

**Comment by codeshaunted** [comment]
> I think many of the cpp files in the cryptolib thing can be removed since it makes the compilation time much longer

You can add CMake configuration to only build the AES parts that I use if you'd like.
